services:
  - type: web
    name: n8n-render
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile

    envVars:
      - key: N8N_PORT
        value: "5678"

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        value: "venkie"

      - key: N8N_BASIC_AUTH_PASSWORD
        value: "venkates2007!"

      - key: N8N_PROTOCOL
        value: "https"

      # Must be your actual Render domain
      - key: N8N_HOST
        value: "n8nr-tng3.onrender.com"

      # Recommended for webhooks
      - key: WEBHOOK_URL
        value: "https://n8nr-tng3.onrender.com/"

      # SQLite database location
      - key: DB_SQLITE_DATABASE
        value: /home/node/.n8n/data/database.sqlite
